import '../styles/global.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

const geistSans = Geist({
    variable: '--font-geist-sans',
 });

const geistMono = Geist_Mono({
     variable: '--font-geist-mono',
});

export const metadata: Metadata = {
    title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
    children: React.ReactNode;
  }) {
     return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
          <body>
               {children}
           </body>
         </html>
      );
 }